{% set name = "braceexpand" %}
{% set version = "0.1.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: e6e539bd20eaea53547472ff94f4fb5c3d3bf9d0a89388c4b56663aba765f705

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - braceexpand

about:
  home: "https://github.com/trendels/braceexpand"
  license: "MIT"
  license_family: "MIT"
  license_file: "LICENSE"
  summary: "Bash-style brace expansion for Python"

extra:
  recipe-maintainers:
    - ap--
    - cbrueffer
